/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import * as THREE from "three";
import { useControls } from "leva";

export function Mountain2(props) {
  const { nodes, materials } = useGLTF("/mountain3.gltf");
  const texture = useLoader(THREE.TextureLoader, "/T_Mountains_winter_32.png");
  const { rotation, position } = useControls("Mountain2", {
    rotation: {
      value: { x: 0, y: 0, z: 0 },
      step: 0.01,
    },
    position: {
      value: { x: 0, y: 0, z: 0 },
      step: 0.1,
    },
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mountain_winter_003.geometry}
        material={materials["Material #25.002"]}
        scale={0.01}
        position={[position.x, position.y, position.z]}
        rotation={[rotation.x, rotation.y, rotation.z]}
      >
        <meshMatcapMaterial map={texture} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/mountain2.gltf");
