/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import * as THREE from "three";

export function Mountain(props) {
  const { nodes, materials } = useGLTF("/mountain1.gltf");
  const texture = useLoader(THREE.TextureLoader, "/T_Mountains_winter_32.png");
  // Adjust these values to fit your texture properly
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mountain_winter_009.geometry}
        material={materials["Material #25.003"]}
        scale={0.01}
        position={[20, 0, 30]}
      >
        <meshMatcapMaterial map={texture} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/mountain1.gltf");
